export const RELOAD = "RELOAD"
export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER"
export const SET_TOAST = "SET_TOAST"

export const SET_TEMPLATES = "SET_TEMPLATES"
export const SET_ACTIVE_TEMPLATE = "SET_ACTIVE_TEMPLATE"
export const SHOW_ADD_STUDENTS_POPUP = "SHOW_ADD_STUDENTS_POPUP"

export const SET_STUDENTS = "SET_STUDENTS"
export const SET_STUDENT_FIELDS = "SET_STUDENT_FIELDS"